config/routes.rb
Kip::Application.routes.draw do

  devise_for :users

  resources :itineraries
  resources :activities
  resources :family_deals

  root :to => "itineraries#index"
  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  # attr_accessible :title, :body

  acts_as_gmappable

  def gmaps4rails_address
    "#{self.street}, #{self.city}, #{self.country}"
  end

  def gmaps4rails_infowindow
    "
      <h3>#{self.name}</h3>
      <img src='#{self.image_url}' style='float:left;'>
      <div>
        <p>#{self.street}</p>
        <p><a href='#{self.link}'>More Information</a></p>
      </div>
    "
  end

end

app/models/family_deal.rb
class FamilyDeal < ActiveRecord::Base
  attr_accessible :ls_id, :link, :title, :long_title, :deal_type, :merchandise_type, :market_id, :market_name, :market_location, :featureType, :country_code, :subtitle, :image_url, :categories, :address1, :address2, :city, :state, :zip

end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  attr_accessible :id, :name, :ls_deal_id, :user_id

  has_many :itinerary_activities
  has_many :activities, :through => :itinerary_activities
end

app/models/itinerary_activity.rb
class ItineraryActivity < ActiveRecord::Base
  # attr_accessible :title, :body

  belongs_to :itinerary
  belongs_to :activity
end

app/models/living_social_deal.rb
class LivingSocialDeal
  include Mongoid::Document

  field :ls_id
  field :published
  field :link
  field :title
  field :long_title
  field :deal_type
  field :merchandise_type
  field :market_id
  field :market_name
  field :market_location, type: Array
  field :featureType
  field :country_code
  field :subtitle
  field :offer_ends_at
  field :price
  field :value
  field :savings
  field :order_count
  field :merchant_type
  field :image_url
  field :categories
  field :sold_out
  field :national
  field :description
  field :details
  field :content
  field :merchant
  field :address1
  field :address2
  field :city
  field :state
  field :zip

  index(
    [[:market_location, Mongo::GEO2D]], background: true
  )

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/family_deals_controller.rb
class FamilyDealsController < ApplicationController

  STATE_ABBREVIATIONS = [ "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
                          "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
                          "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
                          "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
                          "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY" ]
  def index
    if current_user.email == ADMIN_EMAIL
      @family_deals = FamilyDeal.all
    else
      redirect_to root_path
    end
  end

  def new
    if current_user.email == ADMIN_EMAIL
      @deal = FamilyDeal.new
      @living_social_deals = get_families_deals
    else
      redirect_to root_path
    end
  end

  def create
    if current_user.email == ADMIN_EMAIL
      old_families_deals = FamilyDeal.all
      old_families_deals_titles = old_families_deals.collect do |deal|
        deal.long_title
      end
      build_new_families_deals(old_families_deals_titles)
      redirect_to family_deals_path
    else
      redirect_to root_path
    end
  end
  
  private

  def get_families_deals
    family_deals = LivingSocialDeal.where(deal_type:"FamiliesDeal")
    us_deals_with_address = []
    family_deals.each do |deal|
      if STATE_ABBREVIATIONS.include?(deal.state) && deal.address1 != nil
        us_deals_with_address << deal
      end
    end
    deals = dedup(us_deals_with_address)
    sample(deals)
  end

  def sample(deals)
    deals[0..9]
  end

  def dedup(deals)
    titles = []
    deduped_deals = []
    deals.each do |deal|
      unless titles.include?(deal.long_title)
        deduped_deals << deal
        titles << deal.long_title
      end
    end
    deduped_deals
  end

  def build_new_families_deals(old_families_deals_titles)
    get_families_deals.each do |deal|
      unless old_families_deals_titles.include?(deal.long_title)
        create_new_families_deal(deal)
        create_activity(deal)
      end
    end
  end

  def create_new_families_deal(deal)
    new_deal = FamilyDeal.new
    new_deal.long_title = deal.long_title
    new_deal.deal_type = deal.deal_type
    new_deal.market_name = deal.market_name
    new_deal.country_code = deal.country_code
    new_deal.categories = deal.categories
    new_deal.address1 = deal.address1
    new_deal.address2 = deal.address2
    new_deal.city = deal.city
    new_deal.state = deal.state
    new_deal.zip = deal.zip
    new_deal.country = "USA"
    new_deal.image_url = deal.image_url
    new_deal.categories = deal.categories
    new_deal.link = deal.link
    new_deal.save
  end

  def create_activity(deal)
    new_activity = Activity.new
    new_activity.name = deal.long_title
    new_activity.street = deal.address1
    new_activity.city = deal.city
    new_activity.country = "USA"
    new_activity.deal = true
    new_activity.image_url = deal.image_url
    new_activity.categories = deal.categories
    new_activity.link = deal.link
    new_activity.save
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  def index
    unless current_user
      redirect_to new_user_session_path
    else
      @itineraries = Itinerary.find_all_by_user_id(current_user.id)
      if @itineraries == []
        @empty_message = "You haven't created any itineraries yet! Why don't you get started?"
      end
    end
  end

  def show
    @itinerary = Itinerary.find(params[:id])
    @activities = @itinerary.activities
    @mapped_activities = @activities
    @json = @mapped_activities.to_gmaps4rails
  end

  def new
    @itinerary = Itinerary.new
    @deals = Activity.find_all_by_deal(true)
  end

  def create
    @itinerary = Itinerary.new(params[:itinerary])
    @itinerary.save

    flash[:message] = "Itinerary Created"

    redirect_to edit_itinerary_path(@itinerary)
  end

  def destroy
    @itinerary = Itinerary.find(params[:id])
    @itinerary.destroy
    redirect_to itineraries_path
  end

  def edit
    @itinerary = Itinerary.find(params[:id])
    @current_activities = @itinerary.activities

    @deal = @deal || this_itinerary_deal
    if @deal
      build_available_activities(@deal.id)
    end

    @deals = Activity.find_all_by_deal(true)

    @activity_map = @current_activities.to_gmaps4rails
  end

  def update
    @itinerary = Itinerary.find(params[:id])
    @activity = Activity.find(params[:itinerary][:activity_id])
    @itinerary.activities << @activity

    flash[:message] = "#{@activity.name} added to #{@itinerary.name}"
    redirect_to edit_itinerary_path(@itinerary)
  end

  private

  def this_itinerary_deal
    deal = @current_activities.each do |activity|
      if activity.deal == true
        activity
      end
    end
    deal = deal.first
  end

  def build_available_activities(deal_id)
    @available_activities = []
    all_activities = Activity.find_all_by_deal_activity_id(deal_id)
    all_activities.each do |activity|
      if activity.deal == false 
        unless @current_activities.include?(activity)
          @available_activities << activity
        end
      end
    end
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/family_deals_helper.rb
module FamilyDealsHelper

end

app/helpers/itineraries_helper.rb
module ItinerariesHelper


  def itinerary_photo_url(id)
    activities = Itinerary.find(id).activities
    deal_activity = nil
    activities.each do |activity|
      if activity.deal == true
        deal_activity = activity
      end
    end
    if deal_activity
      deal_activity.image_url
    end
  end

  def deal_name(itinerary_id)
    activities = Itinerary.find(itinerary_id).activities
    deal_activity = nil
    activities.each do |activity|
      if activity.deal == true
        deal_activity = activity
      end
    end
    deal_activity
  end

end

app/helpers/itinerary_activities_helper.rb
module ItineraryActivitiesHelper
end

app/views/itineraries/_activity_picker.html.erb
<div class="span5">
  <h3><small>Step 3:</small> Add Activities</h3>
  <table class="table">
    <% @available_activities.each do |activity| %>
      <%= form_for @itinerary do |f| %>
        <%= f.hidden_field :activity_id, :value => activity.id %>
        <tr>
          <td><%= activity.name %></td>
          <td><%= activity.street %></td>
          <td><%= activity.city %></td>
          <td><%= activity.country %></td>
          <td><%= activity.phone %></td>
          <td><%= f.submit "Add to Itinerary" %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/itineraries/_current_activities_list.html.erb
<div>
  <table id="itinerary">
    <% @current_activities.each do |activity| %>
      <tr>
        <td><%= link_to activity.name, activity.link %></td>
        <td><%= activity.street %></td>
        <td><%= activity.city %></td>
        <td><%= activity.country %></td>
        <td><%= activity.phone %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/itineraries/_deal_panel.html.erb
<div id="deal" class="span3 well">
  <h2>The Deal:</h2>
  <h3><%= @deal.name %></h3>
  <p><%= @deal.street %><br />
    <%= @deal.city %></p>
</div>

app/views/itineraries/_deal_picker.html.erb
<p>Congratulations, you're on the way to a fantastic day! Pick which LivingSocial Families deal you'd like to plan your day around.</p>
<div id="deal_pick" class="well">
  <h2><small>Step 2:</small> Pick your Deal</h2>
  <div class="deal_pick_panel">
    <table class="table">
      <% @deals.each do |deal| %>
        <%= form_for @itinerary do |f| %>
          <%= f.hidden_field :activity_id, :value => deal.id %>
          <tr id="deal_<%= deal.id %>">
            <td><%= deal.name %></td>
            <td><%= deal.city %></td>
            <td><%= f.submit "Add to Itinerary", class: "btn" %></td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>
</div>

app/views/itineraries/edit.html.erb
<div class="row" style="margin-top:20px;">
  <div class="span6">
    <h2><small>Planning For:</small> <%= @itinerary.name %></h2>
  </div>
  <div class="span3">
    <div class="btn-group">
      <%= link_to "Save Itinerary", itinerary_path(@itinerary), class: "btn btn-primary" %>
      <%= link_to "Delete Itinerary", itinerary_path(@itinerary), method: "delete", class: "btn btn-danger" %>
    </div>
  </div>
</div>

<% unless @current_activities = [] %>
  <h3>Currently in Itinerary</h3>
  <%= render "current_activities_list" %>
<% end %>

<% if @deal %>

  <div class="row">
    <div class="span8" style="margin-bottom:20px;">
      <%= gmaps4rails(@activity_map) %>
    </div>
  </div>

  <div class="row">
    <%= render "deal_panel" %>
    <%= render "activity_picker" %>
  </div>
<% else %>
  <%= render "deal_picker" %>
<% end %>

app/views/itineraries/index.html.erb
<div class="row">
  <div class="span6">
    <h2 id="itinerary_title">Your Plans</h2>
  </div>
  <div class="span2">
    <%= link_to "Create itinerary", new_itinerary_path, class: "btn btn-primary" %>
  </div>
</div>
<div id="itinerary_list">
  <% if @itineraries == [] %>
    <p id="empty_itinerary_message"><%= @empty_message %></p>
  <% else %>
    <% @itineraries.each do |itinerary| %>
      <div class="itinerary_item span2 well" style="text-align: center">
        <h3><%= link_to itinerary.name, itinerary_path(itinerary) %></h3>
        <%= link_to (image_tag itinerary_photo_url(itinerary.id)), itinerary_path(itinerary) %>
      </div>
    <% end %>
  <% end %>
</div>  
  

app/views/itineraries/new.html.erb
<h2><small>Step 1:</small> Name your Itinerary</h2>
<p><span>Every itinerary needs a name. Otherwise, how will you know which one it is?</p>
<%= form_for @itinerary do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div>
    <%= f.label "What's the name of your next adventure?" %>
    <%= f.text_field :name, class: "span9", id: :name %>
  </div>
  <div>
    <%= f.submit "Start Building", class: "btn" %>
  </div>
<% end %>

app/views/itineraries/show.html.erb
<h2><%= @itinerary.name %></h2>
<div class="row">
  <div class="span5">
    <p>Here's your trip! You can view it online here whenever you'd like or print it out and take it with you on the go.</p>
  </div>
  <div class="span4">
    <div class="btn-group pull-right">  
      <%= link_to "Back to all itineraries", itineraries_path, class: "btn" %>
      <%= link_to "Edit this Itinerary", edit_itinerary_path(@itinerary), class: "btn btn-primary" %>
      <%= link_to "Delete", itinerary_path(@itinerary), method: "delete", class: "btn btn-danger" %>
    </div>
  </div>
</div>

<div style="margin-bottom:20px;">
  <%= gmaps4rails(@json) %></p>
</div>

<table class="table" id="itinerary">
  <% @activities.each do |activity| %>
    <tr>
      <td><%= activity.name %></td>
      <td><%= activity.street %></td>
      <td><%= activity.city %></td>
      <td><%= activity.country %></td>
      <td><%= activity.phone %></td>
    </tr>
  <% end %>
</table>